services:
  - type: web
    name: foosball-rating
    env: node
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: MONGODB_URI
        sync: false
      - key: MONGODB_DB
        value: foosball
      - key: PORT
        value: 10000 